// Terminal specific timeline data
export const TERMINAL_TIMELINE_DATA = [
  {
    date: "2022.4",
    output: "Entered Shibaura Institute of Technology",
    description: "Started studying in Computer Science Department",
    link: "https://www.shibaura-it.ac.jp/",
    type: "education",
  },
  {
    date: "2023.5",
    output: "Recruit Co., Ltd.",
    description: "Frontend development (10 months)",
    link: "https://www.recruit.co.jp/",
    type: "work",
  },
  {
    date: "2023.11",
    output: "MichibikuGroup Co., Ltd.",
    description: "Frontend development (2 months)",
    link: "https://michibikugroup.co.jp/",
    type: "work",
  },
  {
    date: "2024.3",
    output: "Founded TechNova as Representative",
    description: "Established programming circle",
    link: "https://x.com/ShibaYoko_SIT",
    type: "leadership",
  },
  {
    date: "2024.4",
    output: "How Television Co., Ltd.",
    description: "Frontend development (3 months)",
    link: "https://howtelevision.co.jp/",
    type: "work",
  },
  {
    date: "2024.9",
    output: "LayerX Inc.",
    description: "Full-stack development (2 weeks)",
    link: "https://layerx.co.jp/",
    type: "work",
  },
  {
    date: "2024.12",
    output: "Medley Inc.",
    description: "Full-stack development (2 weeks)",
    link: "https://www.medley.jp/",
    type: "work",
  },
  {
    date: "2025.1",
    output: "NOT A HOTEL Inc.",
    description: "New feature development (2 weeks)",
    link: "https://notahotel.com/",
    type: "work",
  },
  {
    date: "2025.2",
    output: "Founded ShibaYoko as Representative",
    description: "Established engineer-designer circle",
    link: "https://x.com/ShibaYoko_SIT",
    type: "leadership",
  },
  {
    date: "2025.3",
    output: "Nulogic Inc.",
    description: "New feature development (2 months)",
    link: "https://nulogic.co.jp/",
    type: "work",
  },
  {
    date: "2025.5 - 2025.7",
    output: "Mercari Inc. (Mercari Hallo)",
    description: "Frontend development (3 months)",
    link: "https://hallo.mercari.com/",
    type: "work",
  },
];