// Terminal specific timeline data for ShibaYoko
export const TERMINAL_TIMELINE_DATA = [
  {
    date: "2024.3",
    output: "TechNova サークル設立",
    description: "エンジニア向けプログラミング学習サークルを設立",
    link: "https://x.com/ShibaYoko_SIT",
    type: "leadership",
  },
  {
    date: "2024.4",
    output: "初回勉強会開催",
    description: "React・Next.jsの基礎勉強会を実施",
    link: "",
    type: "education",
  },
  {
    date: "2024.6",
    output: "デザイナーメンバー加入",
    description: "デザイン志望の学生たちとの出会いと融合",
    link: "",
    type: "community",
  },
  {
    date: "2024.8",
    output: "夏合宿実施",
    description: "2泊3日でチーム開発プロジェクトに挑戦",
    link: "",
    type: "education",
  },
  {
    date: "2024.10",
    output: "学園祭出展",
    description: "開発したWebアプリケーションのデモンストレーション",
    link: "",
    type: "community",
  },
  {
    date: "2024.12",
    output: "しばよこに名称変更",
    description: "TechNovaからしばよこへリブランディング",
    link: "https://note.com/shibayoko_sit/n/n3e5a6d4d6e51",
    type: "leadership",
  },
  {
    date: "2025.1",
    output: "公式Xアカウント開設",
    description: "情報発信とコミュニティ拡大を開始",
    link: "https://x.com/ShibaYoko_SIT/status/1899298064772550860",
    type: "community",
  },
  {
    date: "2025.3",
    output: "新メンバー募集開始",
    description: "2025年度新入生向けメンバー募集を開始",
    link: "https://x.com/ShibaYoko_SIT/status/1943853851783967146",
    type: "community",
  },
  {
    date: "2025.8",
    output: "公式サイト開設",
    description: "Next.js・TypeScriptで構築した公式Webサイトを公開",
    link: "https://shibayoko.vercel.app/",
    type: "leadership",
  },
];